### ISSUE TITLE
symbol_to_maps.py excludes .text section

### ISSUE THREAD

**Issue by Pokechu22** [jdaster64/ttyd-utils#1]
The script to convert from the `.csv` file to a `.map` file doesn't include symbols in the `.text` section, which seems like an odd choice.  This makes the generated map file not particularly helpful for importing into Ghidra (and I suspect it wouldn't be useful in Dolphin either, as I don't think Dolphin makes use of symbols for data, only for functions).  Is there any reason why it's set up like this?  Adding `.text` to the list of sections seemed to work fine for me.

https://github.com/jdaster64/ttyd-utils/blob/191fdf396010dd241aaeba77c97aa728f75863e3/source/symbol_to_maps.py#L80-L82

**Comment by jdaster64** [comment]
Whoops, not sure why that was missing; it's fixed now.
